/**
 * Localized message catalog — everything the AGENT says that is not generated by the LLM.
 *
 * WHY these strings are data and not prompt output: they are said at moments where we
 * cannot afford a model round-trip (fillers, no-input reprompts) or where the wording is
 * legally load-bearing (the AI disclosure, docs/14 / EU AI Act). Both cases need a string
 * that is fixed, reviewed, and translated by a human — not paraphrased per call.
 *
 * REGISTER IS ENFORCED BY THE TYPE SYSTEM. For any locale whose `tv` field in locales.ts
 * is non-null, every catalog entry must supply BOTH a `formal` and an `informal` variant.
 * Omitting one is a compile error, not a runtime surprise where a German customer hears
 * "du" from a bank's agent. docs/13 §4: getting this wrong is offensive in a way English
 * has no equivalent for.
 *
 * TRANSLATION RULES followed here:
 *   - Idiomatic, not translated-from-English. German says "Einen Moment, ich schaue nach.",
 *     never a literal rendering of "let me check that for you".
 *   - Register is consistent within a string AND within a locale.
 *   - Where a language's polite form is gendered (pl Pan/Pani, pt-BR o senhor/a senhora)
 *     the formal variant uses an impersonal construction instead, because we do not know
 *     the caller's gender and guessing it is worse than avoiding it.
 *   - Regional variants differ only where it genuinely matters (es-MX preterite vs es-ES
 *     present perfect, pt-PT "estar a fazer" vs pt-BR gerund, fr-CA/fr-BE idiom).
 *
 * Locales we are not confident in are marked `beta` in locales.ts and are therefore absent
 * from `CatalogLocale`; they resolve through the Localizer's logged fallback chain instead.
 */

import type { CatalogLocale, TvLocale } from './locales.js';

/** Both registers, required together. */
export interface ByRegister<T> {
  readonly formal: T;
  readonly informal: T;
}

/** T-V locales get a register pair; everything else gets the bare value. */
export type Registered<L extends CatalogLocale, T> = L extends TvLocale ? ByRegister<T> : T;

/** A complete translation set. Missing locale OR missing register => compile error. */
export type Catalog<T> = { readonly [L in CatalogLocale]: Registered<L, T> };

/** Escalating no-input ladder: nudge, explicit instruction, graceful exit. docs/03 2.11. */
export type RepromptLadder = readonly [string, string, string];
export type RepromptLevel = 1 | 2 | 3;

export type ErrorKind = 'line_quality' | 'no_understand' | 'wrapping_up';
export type ErrorMessages = { readonly [K in ErrorKind]: string };

/** Substituted with the recognised value by `Localizer.confirm()`. */
export const CONFIRM_PLACEHOLDER = '{value}';

// ---------------------------------------------------------------------------
// AI disclosure — EU AI Act transparency obligation (docs/14, docs/13 §2)
//
// Always spoken in the FORMAL register regardless of the agent's configured register:
// this is a legal statement, and the informal variants exist only because the type
// demands symmetry (and because an agent that is informal throughout would sound
// bizarre switching to Sie for one sentence in a low-stakes consumer flow).
// `Localizer.disclosure()` ignores the register preference and always returns formal.
// ---------------------------------------------------------------------------

export const aiDisclosure = {
  'en-US': "Just so you know, you're speaking with an AI assistant.",
  'en-GB': "Just to let you know, you're speaking to an AI assistant.",
  'en-AU': "Before we start, I should let you know you're speaking with an AI assistant.",
  'en-IE': "Just to let you know, you're speaking with an AI assistant.",

  'de-DE': {
    formal: 'Ich möchte Sie darauf hinweisen, dass Sie mit einem KI-Assistenten sprechen.',
    informal: 'Nur damit du es weißt: Du sprichst mit einem KI-Assistenten.',
  },
  'de-AT': {
    // "Ich darf Sie darauf hinweisen" is the standard Austrian phone register.
    formal: 'Ich darf Sie darauf hinweisen, dass Sie mit einem KI-Assistenten sprechen.',
    informal: 'Damit du Bescheid weißt: Du sprichst mit einem KI-Assistenten.',
  },

  'fr-FR': {
    formal: 'Je tiens à vous informer que vous parlez avec un assistant IA.',
    informal: 'Je te préviens : tu parles avec un assistant IA.',
  },
  'fr-BE': {
    formal: 'Pour votre information, vous parlez avec un assistant IA.',
    informal: 'Pour info, tu parles avec un assistant IA.',
  },
  'fr-CA': {
    formal: 'Sachez que vous parlez avec un assistant IA.',
    informal: 'Juste pour que tu le saches, tu parles avec un assistant IA.',
  },

  'es-ES': {
    formal: 'Le informo de que está hablando con un asistente de inteligencia artificial.',
    informal: 'Te aviso de que estás hablando con un asistente de inteligencia artificial.',
  },
  'es-MX': {
    // Mexican usage drops the "de" that peninsular Spanish keeps in "informar de que".
    formal: 'Le informo que está hablando con un asistente de inteligencia artificial.',
    informal: 'Te aviso que estás hablando con un asistente de inteligencia artificial.',
  },

  'it-IT': {
    formal: 'La informo che sta parlando con un assistente di intelligenza artificiale.',
    informal: 'Ti avviso che stai parlando con un assistente di intelligenza artificiale.',
  },

  'nl-NL': {
    formal: 'Ter informatie: u spreekt met een AI-assistent.',
    informal: 'Even ter info: je spreekt met een AI-assistent.',
  },
  'nl-BE': {
    formal: 'Voor alle duidelijkheid: u spreekt met een AI-assistent.',
    informal: 'Even ter info: je spreekt met een AI-assistent.',
  },

  'pt-PT': {
    formal: 'Informo que está a falar com um assistente de inteligência artificial.',
    informal: 'Aviso-te que estás a falar com um assistente de inteligência artificial.',
  },
  'pt-BR': {
    // Formal drops the pronoun entirely: "o senhor / a senhora" would force a gender guess.
    formal: 'Informo que está falando com um assistente de inteligência artificial.',
    informal: 'Só para você saber: você está falando com um assistente de inteligência artificial.',
  },

  'pl-PL': {
    // Impersonal construction avoids the gendered Pan/Pani entirely.
    formal: 'Informuję, że ta rozmowa jest prowadzona z asystentem AI.',
    informal: 'Uprzedzam, że rozmawiasz z asystentem AI.',
  },
} satisfies Catalog<string>;

// ---------------------------------------------------------------------------
// Fillers — spoken when a tool call exceeds the ~500ms dead-air budget (docs/03 1.8).
//
// These must sound like a person stalling, not like a translated UI string. They are
// short on purpose: the tool result usually lands mid-filler, and a long filler forces
// either a talk-over or an awkward pause.
// ---------------------------------------------------------------------------

export const fillers = {
  'en-US': ['One moment.', 'Let me pull that up.', 'Just checking on that.', 'Hang on one second.', 'Okay — looking into it now.'],
  'en-GB': ['One moment.', 'Let me just check that for you.', 'Bear with me a second.', 'Just looking that up now.', 'Right, give me a moment.'],
  'en-AU': ['One sec.', 'Let me check that for you.', 'Bear with me.', 'Just looking that up now.', 'No worries — one moment.'],
  'en-IE': ['One moment now.', 'Let me just check that for you.', 'Bear with me a second.', "I'm looking that up now.", 'Grand — just a moment.'],

  'de-DE': {
    formal: ['Einen Moment, ich schaue nach.', 'Kurz bitte.', 'Das prüfe ich für Sie.', 'Einen kleinen Augenblick.', 'Ich sehe gerade nach.'],
    informal: ['Einen Moment, ich schaue nach.', 'Kurz bitte.', 'Das schaue ich für dich nach.', 'Einen kleinen Augenblick.', 'Ich sehe gerade nach.'],
  },
  'de-AT': {
    formal: ['Einen Moment bitte, ich schaue nach.', 'Ganz kurz bitte.', 'Das schaue ich Ihnen gleich nach.', 'Einen Augenblick, bitte.', 'Ich sehe gerade nach.'],
    informal: ['Einen Moment, ich schaue nach.', 'Ganz kurz bitte.', 'Das schaue ich dir gleich nach.', 'Einen Augenblick.', 'Ich sehe gerade nach.'],
  },

  'fr-FR': {
    formal: ['Un instant, je vérifie.', 'Je regarde ça tout de suite.', "Un petit instant, s'il vous plaît.", 'Je consulte votre dossier.', 'Voilà, je vous trouve ça.'],
    informal: ['Un instant, je vérifie.', 'Je regarde ça tout de suite.', 'Deux secondes.', 'Je consulte ton dossier.', 'Attends, je te trouve ça.'],
  },
  'fr-BE': {
    // "directement" for "right away" is the Belgicism a Belgian ear expects here.
    formal: ['Un instant, je vérifie.', 'Je regarde ça directement.', "Une petite seconde, s'il vous plaît.", 'Je consulte votre dossier.', 'Je vous trouve ça tout de suite.'],
    informal: ['Un instant, je vérifie.', 'Je regarde ça directement.', 'Une petite seconde.', 'Je consulte ton dossier.', 'Je te trouve ça tout de suite.'],
  },
  'fr-CA': {
    // "Deux minutes" is Québécois for "just a sec" — it does not mean two minutes.
    formal: ['Un instant, je vérifie.', 'Je regarde ça tout de suite.', 'Deux minutes, je vérifie ça.', 'Je consulte votre dossier.', 'Je vous reviens avec ça.'],
    informal: ['Un instant, je vérifie.', 'Je regarde ça tout de suite.', 'Deux minutes, je vérifie ça.', 'Je consulte ton dossier.', 'Je te reviens avec ça.'],
  },

  'es-ES': {
    formal: ['Un momento, lo consulto.', 'Déjeme que lo compruebe.', 'Un segundito, por favor.', 'Lo estoy mirando ahora mismo.', 'Enseguida se lo digo.'],
    informal: ['Un momento, lo consulto.', 'Déjame que lo compruebe.', 'Un segundito.', 'Lo estoy mirando ahora mismo.', 'Enseguida te lo digo.'],
  },
  'es-MX': {
    // "revisar" and "ahorita" are the Mexican reflexes; "comprobar" reads peninsular.
    formal: ['Un momento, permítame verificarlo.', 'Déjeme revisarlo.', 'Un segundito, por favor.', 'Lo estoy revisando ahorita.', 'Enseguida le digo.'],
    informal: ['Un momento, déjame verificarlo.', 'Déjame revisarlo.', 'Un segundito.', 'Lo estoy revisando ahorita.', 'Ahorita te digo.'],
  },

  'it-IT': {
    formal: ['Un attimo, controllo subito.', 'Glielo controllo subito.', 'Un secondo, per favore.', 'Sto verificando.', 'Ecco, ci sono quasi.'],
    informal: ['Un attimo, controllo subito.', 'Te lo controllo subito.', 'Un secondo.', 'Sto verificando.', 'Ecco, ci sono quasi.'],
  },

  'nl-NL': {
    formal: ['Een moment, ik zoek het even op.', 'Ik kijk het even na.', 'Momentje, alstublieft.', 'Ik ben het aan het opzoeken.', 'Even geduld, alstublieft.'],
    informal: ['Een moment, ik zoek het even op.', 'Ik kijk het even na.', 'Momentje.', 'Ik ben het aan het opzoeken.', 'Even geduld.'],
  },
  'nl-BE': {
    // Flemish prefers "dat" where the Netherlands says "het" in this construction.
    formal: ['Een moment, ik zoek dat even op.', 'Ik kijk dat even na.', 'Momentje, alstublieft.', 'Ik ben dat aan het opzoeken.', 'Ik heb het zo voor u.'],
    informal: ['Een moment, ik zoek dat even op.', 'Ik kijk dat even na.', 'Momentje.', 'Ik ben dat aan het opzoeken.', 'Ik heb het zo voor je.'],
  },

  'pt-PT': {
    formal: ['Um momento, vou verificar.', 'Deixe-me confirmar.', 'Só um instante, por favor.', 'Estou a consultar aqui.', 'Já lhe digo.'],
    informal: ['Um momento, vou verificar.', 'Deixa-me confirmar.', 'Só um instante.', 'Estou a consultar aqui.', 'Já te digo.'],
  },
  'pt-BR': {
    formal: ['Um momento, vou verificar.', 'Só um instante, por favor.', 'Estou consultando aqui.', 'Deixe-me confirmar.', 'Já lhe informo.'],
    informal: ['Um momento, vou verificar.', 'Só um segundinho.', 'Estou consultando aqui.', 'Deixa eu confirmar.', 'Já te falo.'],
  },

  'pl-PL': {
    formal: ['Chwileczkę, już sprawdzam.', 'Momencik, proszę.', 'Już to sprawdzam.', 'Sekundkę, zaraz sprawdzę.', 'Zaraz podam informację.'],
    informal: ['Chwileczkę, już sprawdzam.', 'Momencik.', 'Już to sprawdzam.', 'Sekundkę, zaraz sprawdzę.', 'Zaraz ci powiem.'],
  },
} satisfies Catalog<readonly string[]>;

// ---------------------------------------------------------------------------
// Reprompts — the no-input ladder (docs/03 2.11).
// Level 1 nudges, level 2 states the problem and gives an instruction, level 3 exits
// gracefully and invites a call back. Level 3 must never sound like a hang-up in anger.
// ---------------------------------------------------------------------------

export const reprompts = {
  'en-US': [
    'Sorry, are you still there?',
    "I still can't hear anything — if you can hear me, go ahead and speak.",
    "I'm not hearing anything, so I'll let you go. Feel free to call back any time.",
  ],
  'en-GB': [
    'Sorry, are you still there?',
    "I still can't hear you — if you can hear me, do go ahead.",
    "I'm not hearing anything, so I'll end the call here. Do call back whenever suits.",
  ],
  'en-AU': [
    'Sorry, are you still there?',
    "Still can't hear you — if you can hear me, go ahead.",
    "I'm not hearing anything, so I'll let you go. Give us a call back any time.",
  ],
  'en-IE': [
    'Sorry, are you still there?',
    "I still can't hear you — if you can hear me, go ahead.",
    "I'm not hearing anything at all, so I'll let you go. Ring us back any time.",
  ],

  'de-DE': {
    formal: [
      'Sind Sie noch da?',
      'Ich kann Sie leider nicht hören. Wenn Sie mich hören, sprechen Sie einfach los.',
      'Ich höre leider nichts. Ich beende das Gespräch jetzt — rufen Sie uns gern jederzeit wieder an.',
    ],
    informal: [
      'Bist du noch da?',
      'Ich kann dich leider nicht hören. Wenn du mich hörst, sprich einfach los.',
      'Ich höre leider nichts. Ich beende das Gespräch jetzt — melde dich gern jederzeit wieder.',
    ],
  },
  'de-AT': {
    formal: [
      'Sind Sie noch dran?',
      'Ich kann Sie leider nicht hören. Wenn Sie mich hören, sprechen Sie bitte einfach.',
      'Ich höre leider nichts. Ich beende das Gespräch — rufen Sie uns gern wieder an. Auf Wiederhören.',
    ],
    informal: [
      'Bist du noch dran?',
      'Ich kann dich leider nicht hören. Wenn du mich hörst, sprich einfach.',
      'Ich höre leider nichts. Ich beende das Gespräch — melde dich gern wieder. Auf Wiederhören.',
    ],
  },

  'fr-FR': {
    formal: [
      'Vous êtes toujours là ?',
      "Je ne vous entends pas. Si vous m'entendez, n'hésitez pas à parler.",
      "Je n'entends toujours rien, je vais donc raccrocher. N'hésitez pas à rappeler.",
    ],
    informal: [
      'Tu es toujours là ?',
      "Je ne t'entends pas. Si tu m'entends, parle.",
      "Je n'entends toujours rien, je vais raccrocher. Rappelle quand tu veux.",
    ],
  },
  'fr-BE': {
    formal: [
      'Vous êtes toujours là ?',
      "Je ne vous entends pas. Si vous m'entendez, parlez, je vous en prie.",
      "Je n'entends toujours rien, je vais raccrocher. Vous pouvez rappeler quand vous voulez.",
    ],
    informal: [
      'Tu es toujours là ?',
      "Je ne t'entends pas. Si tu m'entends, parle.",
      "Je n'entends toujours rien, je vais raccrocher. Tu peux rappeler quand tu veux.",
    ],
  },
  'fr-CA': {
    formal: [
      'Êtes-vous toujours là ?',
      "Je ne vous entends pas. Si vous m'entendez, allez-y, parlez.",
      "Je n'entends toujours rien, alors je vais raccrocher. Rappelez-nous quand vous voulez.",
    ],
    informal: [
      'Es-tu toujours là ?',
      "Je ne t'entends pas. Si tu m'entends, vas-y, parle.",
      "Je n'entends toujours rien, alors je vais raccrocher. Rappelle-nous quand tu veux.",
    ],
  },

  'es-ES': {
    formal: [
      '¿Sigue ahí?',
      'No le escucho. Si me oye, hable cuando quiera.',
      'No consigo escuchar nada, así que voy a colgar. Puede llamarnos de nuevo cuando quiera.',
    ],
    informal: [
      '¿Sigues ahí?',
      'No te escucho. Si me oyes, habla cuando quieras.',
      'No consigo escuchar nada, así que voy a colgar. Llámanos cuando quieras.',
    ],
  },
  'es-MX': {
    formal: [
      '¿Sigue ahí?',
      'No se escucha nada por aquí. Si me escucha, hable por favor.',
      'No alcanzo a escuchar nada, así que voy a colgar. Puede marcarnos de nuevo cuando guste.',
    ],
    informal: [
      '¿Sigues ahí?',
      'No se escucha nada por aquí. Si me escuchas, habla por favor.',
      'No alcanzo a escuchar nada, así que voy a colgar. Márcanos cuando gustes.',
    ],
  },

  'it-IT': {
    formal: [
      'È ancora in linea?',
      'Non riesco a sentirla. Se mi sente, parli pure.',
      'Non sento nulla, quindi chiudo la chiamata. Ci richiami quando vuole.',
    ],
    informal: [
      'Ci sei ancora?',
      'Non riesco a sentirti. Se mi senti, parla pure.',
      'Non sento nulla, quindi chiudo la chiamata. Richiamaci quando vuoi.',
    ],
  },

  'nl-NL': {
    formal: [
      'Bent u er nog?',
      'Ik hoor u niet. Als u mij hoort, zegt u het maar.',
      'Ik hoor helaas niets, dus ik beëindig het gesprek. U kunt altijd terugbellen.',
    ],
    informal: [
      'Ben je er nog?',
      'Ik hoor je niet. Als je mij hoort, zeg het maar.',
      'Ik hoor helaas niets, dus ik hang op. Je kunt altijd terugbellen.',
    ],
  },
  'nl-BE': {
    formal: [
      'Bent u daar nog?',
      'Ik hoor u niet. Als u mij hoort, zegt u het gerust.',
      'Ik hoor helaas niets, dus ik rond het gesprek af. U mag altijd terugbellen.',
    ],
    informal: [
      'Ben je daar nog?',
      'Ik hoor je niet. Als je mij hoort, zeg het gerust.',
      'Ik hoor helaas niets, dus ik rond het gesprek af. Je mag altijd terugbellen.',
    ],
  },

  'pt-PT': {
    formal: [
      'Ainda está aí?',
      'Não consigo ouvir nada. Se me estiver a ouvir, pode falar.',
      'Continuo sem ouvir nada, por isso vou terminar a chamada. Pode ligar-nos novamente quando quiser.',
    ],
    informal: [
      'Ainda estás aí?',
      'Não consigo ouvir nada. Se me estiveres a ouvir, fala.',
      'Continuo sem ouvir nada, por isso vou desligar. Liga-nos quando quiseres.',
    ],
  },
  'pt-BR': {
    formal: [
      'Ainda está aí?',
      'Não estou conseguindo ouvir. Se estiver me ouvindo, pode falar.',
      'Continuo sem ouvir nada, então vou encerrar a ligação. Pode ligar de novo quando quiser.',
    ],
    informal: [
      'Você ainda está aí?',
      'Não estou conseguindo te ouvir. Se estiver me ouvindo, pode falar.',
      'Continuo sem ouvir nada, então vou encerrar. Liga de novo quando quiser.',
    ],
  },

  'pl-PL': {
    formal: [
      'Czy nadal jesteśmy połączeni?',
      'Nadal nic nie słyszę. Jeśli mnie słychać, proszę mówić.',
      'Niestety nic nie słyszę, więc zakończę rozmowę. Zapraszam do ponownego kontaktu.',
    ],
    informal: [
      'Jesteś tam jeszcze?',
      'Nadal cię nie słyszę. Jeśli mnie słyszysz, mów śmiało.',
      'Nic nie słyszę, więc się rozłączę. Zadzwoń, kiedy chcesz.',
    ],
  },
} satisfies Catalog<RepromptLadder>;

// ---------------------------------------------------------------------------
// Handoff — transferring to a human.
// Phrased without a gendered noun for the colleague wherever the language allows it
// (de "unser Team", it "un collega" is epicene, es "alguien del equipo").
// ---------------------------------------------------------------------------

export const handoff = {
  'en-US': 'Let me put you through to someone on the team. One moment.',
  'en-GB': "I'll put you through to a colleague now. One moment, please.",
  'en-AU': "I'll put you through to someone on the team. Just a moment.",
  'en-IE': "I'll put you through to one of the team now. One moment, please.",

  'de-DE': {
    formal: 'Ich verbinde Sie jetzt mit unserem Team. Einen Moment, bitte.',
    informal: 'Ich verbinde dich jetzt mit unserem Team. Einen Moment.',
  },
  'de-AT': {
    formal: 'Ich stelle Sie zu unserem Team durch. Einen Moment, bitte.',
    informal: 'Ich stelle dich zu unserem Team durch. Einen Moment.',
  },

  'fr-FR': {
    formal: "Je vous passe un membre de notre équipe. Un instant, s'il vous plaît.",
    informal: 'Je te passe un membre de notre équipe. Un instant.',
  },
  'fr-BE': {
    formal: "Je vous passe quelqu'un de notre équipe. Un instant, s'il vous plaît.",
    informal: "Je te passe quelqu'un de notre équipe. Un instant.",
  },
  'fr-CA': {
    formal: "Je vous transfère à quelqu'un de notre équipe. Un instant, s'il vous plaît.",
    informal: "Je te transfère à quelqu'un de notre équipe. Un instant.",
  },

  'es-ES': {
    formal: 'Le paso con una persona del equipo. Un momento, por favor.',
    informal: 'Te paso con una persona del equipo. Un momento.',
  },
  'es-MX': {
    formal: 'Permítame comunicarle con alguien del equipo. Un momento, por favor.',
    informal: 'Te comunico con alguien del equipo. Un momento.',
  },

  'it-IT': {
    formal: 'Le passo un collega del team. Un attimo, per favore.',
    informal: 'Ti passo un collega del team. Un attimo.',
  },

  'nl-NL': {
    formal: 'Ik verbind u door met een collega. Een moment, alstublieft.',
    informal: 'Ik verbind je door met een collega. Momentje.',
  },
  'nl-BE': {
    formal: 'Ik verbind u door met een collega. Een moment, alstublieft.',
    informal: 'Ik verbind je door met een collega. Momentje.',
  },

  'pt-PT': {
    formal: 'Vou passar a chamada a um colega da equipa. Um momento, por favor.',
    informal: 'Vou passar-te a um colega da equipa. Só um momento.',
  },
  'pt-BR': {
    formal: 'Vou transferir a ligação para alguém da equipe. Um momento, por favor.',
    informal: 'Vou te transferir para alguém da equipe. Só um momento.',
  },

  'pl-PL': {
    formal: 'Przekierowuję rozmowę do naszego zespołu. Proszę chwilę zaczekać.',
    informal: 'Przekierowuję cię do naszego zespołu. Chwilkę.',
  },
} satisfies Catalog<string>;

// ---------------------------------------------------------------------------
// Confirmations — the targeted confirm-back from entity capture (docs/03 §B 2.5).
//
// Deliberately short: this fires only on the low-confidence segment, not on every
// field, so it must not feel like an interrogation. `{value}` is substituted with the
// already-verbalised value (the normalisation layer owns how digits are read aloud).
// ---------------------------------------------------------------------------

export const confirmations = {
  'en-US': 'Just to confirm — did you say {value}?',
  'en-GB': 'Just to check — did you say {value}?',
  'en-AU': 'Just to confirm — was that {value}?',
  'en-IE': 'Just to confirm — did you say {value}?',

  'de-DE': {
    formal: 'Nur zur Sicherheit — Sie haben {value} gesagt, richtig?',
    informal: 'Nur zur Sicherheit — du hast {value} gesagt, richtig?',
  },
  'de-AT': {
    formal: 'Nur zur Sicherheit — Sie haben {value} gesagt, oder?',
    informal: 'Nur zur Sicherheit — du hast {value} gesagt, oder?',
  },

  'fr-FR': {
    formal: 'Pour confirmer, vous avez bien dit {value} ?',
    informal: 'Pour confirmer, tu as bien dit {value} ?',
  },
  'fr-BE': {
    formal: 'Je confirme : vous avez bien dit {value} ?',
    informal: 'Je confirme : tu as bien dit {value} ?',
  },
  'fr-CA': {
    formal: 'Juste pour confirmer, vous avez bien dit {value} ?',
    informal: 'Juste pour confirmer, tu as bien dit {value} ?',
  },

  'es-ES': {
    formal: 'Para confirmar: ¿ha dicho {value}?',
    informal: 'Para confirmar: ¿has dicho {value}?',
  },
  'es-MX': {
    // Mexican Spanish uses the simple preterite where Spain uses the present perfect.
    formal: 'Para confirmar, ¿dijo {value}?',
    informal: 'Para confirmar, ¿dijiste {value}?',
  },

  'it-IT': {
    formal: 'Per conferma: ha detto {value}?',
    informal: 'Per conferma: hai detto {value}?',
  },

  'nl-NL': {
    formal: 'Even ter controle: zei u {value}?',
    informal: 'Even ter controle: zei je {value}?',
  },
  'nl-BE': {
    formal: 'Even ter controle: zei u {value}?',
    informal: 'Even ter controle: zei je {value}?',
  },

  'pt-PT': {
    formal: 'Só para confirmar: disse {value}?',
    informal: 'Só para confirmar: disseste {value}?',
  },
  'pt-BR': {
    formal: 'Só confirmando: disse {value}?',
    informal: 'Só confirmando: você disse {value}?',
  },

  'pl-PL': {
    // "Powtarzam ... zgadza się?" avoids both the gendered honorific and a gendered
    // past-tense verb ("powiedziałeś" / "powiedziałaś"), which we cannot choose safely.
    formal: 'Dla pewności powtarzam: {value}. Czy się zgadza?',
    informal: 'Powtarzam dla pewności: {value}. Zgadza się?',
  },
} satisfies Catalog<string>;

// ---------------------------------------------------------------------------
// Errors.
//   line_quality  — the MOS/loss monitor says the line is degraded (docs/03 §A).
//                   Naming the problem explicitly beats silently mis-hearing the caller.
//   no_understand — ASR returned something, we could not act on it.
//   wrapping_up   — graceful termination for any reason.
// ---------------------------------------------------------------------------

export const errors = {
  'en-US': {
    line_quality: "You're breaking up a little — could you say that again?",
    no_understand: "Sorry, I didn't quite catch that. Could you put it another way?",
    wrapping_up: "I'll need to wrap up here. Thanks for your time.",
  },
  'en-GB': {
    line_quality: "You're breaking up a bit — could you say that again?",
    no_understand: "Sorry, I didn't quite catch that. Could you put it another way?",
    wrapping_up: "I'll wrap things up there. Thanks very much for your time.",
  },
  'en-AU': {
    line_quality: "You're breaking up a bit — can you say that again?",
    no_understand: "Sorry, I didn't quite get that. Can you say it another way?",
    wrapping_up: "I'll wrap up there. Thanks for your time.",
  },
  'en-IE': {
    line_quality: "The line's breaking up a bit — could you say that again?",
    no_understand: "Sorry, I didn't quite catch that. Could you say it another way?",
    wrapping_up: "I'll wrap up there. Thanks a million for your time.",
  },

  'de-DE': {
    formal: {
      line_quality: 'Die Leitung ist gerade sehr schlecht. Könnten Sie das bitte noch einmal sagen?',
      no_understand: 'Entschuldigung, das habe ich nicht verstanden. Können Sie es bitte anders formulieren?',
      wrapping_up: 'Ich muss das Gespräch an dieser Stelle beenden. Vielen Dank für Ihre Zeit.',
    },
    informal: {
      line_quality: 'Die Leitung ist gerade sehr schlecht. Kannst du das bitte noch einmal sagen?',
      no_understand: 'Entschuldigung, das habe ich nicht verstanden. Kannst du es bitte anders sagen?',
      wrapping_up: 'Ich muss das Gespräch an dieser Stelle beenden. Danke für deine Zeit.',
    },
  },
  'de-AT': {
    formal: {
      line_quality: 'Die Leitung ist gerade sehr schlecht. Könnten Sie das bitte noch einmal sagen?',
      no_understand: 'Entschuldigung, das habe ich leider nicht verstanden. Können Sie das bitte anders sagen?',
      wrapping_up: 'Ich beende das Gespräch jetzt. Danke für Ihre Zeit — auf Wiederhören.',
    },
    informal: {
      line_quality: 'Die Leitung ist gerade sehr schlecht. Kannst du das bitte noch einmal sagen?',
      no_understand: 'Entschuldigung, das habe ich leider nicht verstanden. Kannst du das bitte anders sagen?',
      wrapping_up: 'Ich beende das Gespräch jetzt. Danke für deine Zeit — auf Wiederhören.',
    },
  },

  'fr-FR': {
    formal: {
      line_quality: 'La ligne coupe un peu. Pouvez-vous répéter, je vous prie ?',
      no_understand: "Désolé, je n'ai pas bien compris. Pouvez-vous reformuler ?",
      wrapping_up: 'Je vais devoir mettre fin à notre échange. Merci de votre temps et bonne journée.',
    },
    informal: {
      line_quality: 'La ligne coupe un peu. Tu peux répéter ?',
      no_understand: "Désolé, je n'ai pas bien compris. Tu peux reformuler ?",
      wrapping_up: 'Je vais devoir raccrocher. Merci et bonne journée.',
    },
  },
  'fr-BE': {
    formal: {
      line_quality: 'La ligne coupe un peu. Pouvez-vous répéter, je vous prie ?',
      no_understand: "Désolé, je n'ai pas bien compris. Pouvez-vous le redire autrement ?",
      wrapping_up: "Je vais devoir clôturer ici. Merci de votre temps et bonne journée.",
    },
    informal: {
      line_quality: 'La ligne coupe un peu. Tu peux répéter ?',
      no_understand: "Désolé, je n'ai pas bien compris. Tu peux le redire autrement ?",
      wrapping_up: 'Je vais devoir clôturer ici. Merci et bonne journée.',
    },
  },
  'fr-CA': {
    formal: {
      line_quality: "La ligne coupe un peu. Pouvez-vous répéter, s'il vous plaît ?",
      no_understand: "Désolé, je n'ai pas bien compris. Pouvez-vous le dire autrement ?",
      wrapping_up: 'Je vais devoir terminer ici. Merci de votre temps et bonne journée.',
    },
    informal: {
      line_quality: 'La ligne coupe un peu. Peux-tu répéter ?',
      no_understand: "Désolé, je n'ai pas bien compris. Peux-tu le dire autrement ?",
      wrapping_up: 'Je vais devoir terminer ici. Merci et bonne journée.',
    },
  },

  'es-ES': {
    formal: {
      line_quality: 'La línea se está cortando. ¿Puede repetírmelo, por favor?',
      no_understand: 'Perdone, no le he entendido bien. ¿Puede decírmelo de otra manera?',
      wrapping_up: 'Voy a tener que terminar aquí. Gracias por su tiempo.',
    },
    informal: {
      line_quality: 'La línea se está cortando. ¿Puedes repetírmelo?',
      no_understand: 'Perdona, no te he entendido bien. ¿Puedes decírmelo de otra manera?',
      wrapping_up: 'Voy a tener que terminar aquí. Gracias por tu tiempo.',
    },
  },
  'es-MX': {
    formal: {
      line_quality: 'Se está entrecortando la línea. ¿Me lo puede repetir, por favor?',
      no_understand: 'Disculpe, no entendí bien. ¿Me lo puede decir de otra forma?',
      wrapping_up: 'Tengo que terminar la llamada aquí. Gracias por su tiempo.',
    },
    informal: {
      line_quality: 'Se está entrecortando la línea. ¿Me lo puedes repetir?',
      no_understand: 'Disculpa, no entendí bien. ¿Me lo puedes decir de otra forma?',
      wrapping_up: 'Tengo que terminar la llamada aquí. Gracias por tu tiempo.',
    },
  },

  'it-IT': {
    formal: {
      line_quality: 'La linea è disturbata. Può ripetere, per favore?',
      no_understand: 'Mi scusi, non ho capito bene. Può ripetere in altro modo?',
      wrapping_up: 'Devo chiudere qui la chiamata. Grazie per il tempo che mi ha dedicato.',
    },
    informal: {
      line_quality: 'La linea è disturbata. Puoi ripetere?',
      no_understand: 'Scusa, non ho capito bene. Puoi dirlo in un altro modo?',
      wrapping_up: 'Devo chiudere qui la chiamata. Grazie del tempo.',
    },
  },

  'nl-NL': {
    formal: {
      line_quality: 'De verbinding is niet goed. Kunt u dat nog een keer zeggen?',
      no_understand: 'Sorry, dat begreep ik niet helemaal. Kunt u het anders formuleren?',
      wrapping_up: 'Ik ga het gesprek hier afronden. Bedankt voor uw tijd.',
    },
    informal: {
      line_quality: 'De verbinding is niet goed. Kun je dat nog een keer zeggen?',
      no_understand: 'Sorry, dat begreep ik niet helemaal. Kun je het anders zeggen?',
      wrapping_up: 'Ik ga het gesprek hier afronden. Bedankt voor je tijd.',
    },
  },
  'nl-BE': {
    formal: {
      line_quality: 'De verbinding is slecht. Kunt u dat nog eens herhalen?',
      no_understand: 'Sorry, dat heb ik niet goed begrepen. Kunt u het anders zeggen?',
      wrapping_up: 'Ik rond het gesprek hier af. Bedankt voor uw tijd.',
    },
    informal: {
      line_quality: 'De verbinding is slecht. Kun je dat nog eens herhalen?',
      no_understand: 'Sorry, dat heb ik niet goed begrepen. Kun je het anders zeggen?',
      wrapping_up: 'Ik rond het gesprek hier af. Bedankt voor je tijd.',
    },
  },

  'pt-PT': {
    formal: {
      line_quality: 'A linha está a falhar. Pode repetir, por favor?',
      no_understand: 'Desculpe, não percebi bem. Pode dizer de outra forma?',
      wrapping_up: 'Vou ter de terminar a chamada por aqui. Obrigado pelo seu tempo.',
    },
    informal: {
      line_quality: 'A linha está a falhar. Podes repetir?',
      no_understand: 'Desculpa, não percebi bem. Podes dizer de outra forma?',
      wrapping_up: 'Vou ter de terminar a chamada por aqui. Obrigado pelo teu tempo.',
    },
  },
  'pt-BR': {
    formal: {
      line_quality: 'A ligação está falhando um pouco. Pode repetir, por favor?',
      no_understand: 'Desculpe, não entendi bem. Pode dizer de outro jeito?',
      wrapping_up: 'Vou precisar encerrar por aqui. Obrigado pelo seu tempo.',
    },
    informal: {
      line_quality: 'A ligação está falhando um pouco. Pode repetir?',
      no_understand: 'Desculpa, não entendi. Pode falar de outro jeito?',
      wrapping_up: 'Vou precisar encerrar por aqui. Obrigado pelo seu tempo.',
    },
  },

  'pl-PL': {
    formal: {
      line_quality: 'Połączenie jest słabej jakości. Czy mogę prosić o powtórzenie?',
      no_understand: 'Przepraszam, nie udało mi się tego zrozumieć. Proszę powtórzyć innymi słowami.',
      wrapping_up: 'Muszę już zakończyć rozmowę. Dziękuję za poświęcony czas.',
    },
    informal: {
      line_quality: 'Połączenie jest słabej jakości. Możesz powtórzyć?',
      no_understand: 'Przepraszam, nie udało mi się tego zrozumieć. Powiedz to proszę inaczej.',
      wrapping_up: 'Muszę już kończyć. Dzięki za rozmowę.',
    },
  },
} satisfies Catalog<ErrorMessages>;

/** Everything, grouped by purpose. The Localizer is the only intended consumer. */
export const MESSAGES = {
  aiDisclosure,
  fillers,
  reprompts,
  handoff,
  confirmations,
  errors,
} as const;

export type MessageGroup = keyof typeof MESSAGES;

/** Runtime narrowing for the `Registered<L, T>` union — the shape tells us the locale kind. */
export function isByRegister<T>(entry: ByRegister<T> | T): entry is ByRegister<T> {
  return (
    typeof entry === 'object' &&
    entry !== null &&
    !Array.isArray(entry) &&
    'formal' in entry &&
    'informal' in entry
  );
}

/** Collapse a catalog entry to a single value for the requested register. */
export function pickRegister<T>(entry: ByRegister<T> | T, register: 'formal' | 'informal'): T {
  return isByRegister<T>(entry) ? entry[register] : entry;
}
